-- ============================================================
-- Amar Diet — seed: foods (Bangladesh-friendly, low-cost first)
-- Re-run safely: every INSERT uses ON CONFLICT (id) DO NOTHING.
-- Columns: id, name_bn, category, carb_g, protein_g, fat_g, fiber_g,
--          sodium_mg, potassium_mg, phosphorus_mg, gi_category, tags,
--          portion_label, portion_g, affordability, common_in_bd,
--          effort, healthiness
-- ============================================================

-- ---------- breakfast ----------
insert into public.foods (id, name_bn, category, carb_g, protein_g, fat_g, fiber_g, sodium_mg, potassium_mg, phosphorus_mg, gi_category, tags, portion_label, portion_g, affordability, common_in_bd, effort, healthiness) values
('b_lal_ruti',         'লাল আটার রুটি (২টি)',                          'breakfast', 30, 6,  2, 5, 120, 140, 110, 'low',    ARRAY['ckd_caution_moderate','low_sodium_ok','vegetarian']::text[], '২টি মাঝারি',                  60,  'low_cost', true, 'easy',   'good'),
('b_sobji_ruti',       'সবজি রুটি (লাল আটা)',                          'breakfast', 28, 6,  2, 6, 130, 200, 120, 'low',    ARRAY['ckd_caution_moderate','low_sodium_ok','vegetarian']::text[], '২টি রুটি',                    60,  'low_cost', true, 'medium', 'good'),
('b_cha_pata',         'চা + ১টি মুড়ি-চিড়া',                           'breakfast', 22, 3,  1, 2, 60,  80,  50,  'medium', ARRAY['low_sodium_ok','vegetarian']::text[],                          '১ কাপ চা + ৩০গ্রাম চিড়া',     50,  'low_cost', true, 'easy',   'neutral'),
('b_chira_doi',        'চিড়া + টক দই',                                'breakfast', 25, 6,  3, 1, 60,  220, 140, 'medium', ARRAY['low_sodium_ok','vegetarian']::text[],                          'চিড়া ৩০গ্রাম + দই আধা কাপ',   150, 'low_cost', true, 'easy',   'neutral'),
('b_mug_chila',        'মুগ ডালের চিলা',                               'breakfast', 20, 10, 3, 4, 140, 260, 180, 'low',    ARRAY['ckd_restricted_high_phos','vegetarian']::text[],             '২টি ছোট চিলা',                100, 'low_cost', true, 'medium', 'good'),
('b_alt_muri',         'মুড়ি (ভাজা ছাড়া)',                              'breakfast', 24, 2,  0, 1, 180, 40,  30,  'high',   ARRAY['low_potassium_ok','vegetarian']::text[],                       '১ কাপ (৩০ গ্রাম)',           30,  'low_cost', true, 'easy',   'bad'),
('b_oats_khichuri',    'ওটস খিচুড়ি',                                  'breakfast', 27, 8,  3, 6, 150, 180, 130, 'low',    ARRAY['ckd_caution_moderate','low_sodium_ok','vegetarian']::text[], '১ বাটি (৪০ গ্রাম কাঁচা ওটস)', 200, 'medium',  false,'medium', 'good'),
('b_alt_oats_plain',   'ওটস (পানি দিয়ে)',                              'breakfast', 23, 5,  2, 5, 10,  140, 110, 'low',    ARRAY['ckd_caution_moderate','low_sodium_ok','vegetarian']::text[], '৩৫ গ্রাম',                   35,  'medium',  false,'easy',   'good'),
('b_alt_lalchal_ruti', 'লাল আটার রুটি + ডিম',                          'breakfast', 30, 12, 5, 5, 220, 180, 160, 'low',    ARRAY['ckd_caution_moderate','vegetarian_egg']::text[],             '২টি রুটি + ১টি ডিম',         130, 'low_cost', true, 'easy',   'good'),
('b_puli_pitha',       'পুলি পিঠা',                                    'breakfast', 28, 4,  2, 2, 90,  110, 70,  'medium', ARRAY['vegetarian']::text[],                                          '২টি ছোট',                    80,  'low_cost', true, 'hard',   'neutral')
on conflict (id) do nothing;

-- ---------- carb ----------
insert into public.foods (id, name_bn, category, carb_g, protein_g, fat_g, fiber_g, sodium_mg, potassium_mg, phosphorus_mg, gi_category, tags, portion_label, portion_g, affordability, common_in_bd, effort, healthiness) values
('c_lalchal_bhat',     'লাল চালের ভাত (১ কাপ)',                       'carb',     45, 4,  0, 2, 5,   55,  60,  'medium', ARRAY['low_sodium_ok','vegetarian']::text[],                                       '১ কাপ রান্না করা (~১৫০ গ্রাম)',         150, 'low_cost', true, 'easy',   'good'),
('c_lal_ruti_3',       'লাল আটার রুটি (৩টি)',                          'carb',     45, 9,  3, 7, 180, 210, 165, 'low',    ARRAY['ckd_caution_moderate','low_sodium_ok','vegetarian']::text[],              '৩টি মাঝারি',                                90,  'low_cost', true, 'medium', 'good'),
('c_lal_ruti_2',       'লাল আটার রুটি (২টি)',                          'carb',     30, 6,  2, 5, 120, 140, 110, 'low',    ARRAY['ckd_caution_moderate','low_sodium_ok','vegetarian']::text[],              '২টি মাঝারি',                                60,  'low_cost', true, 'easy',   'good'),
('c_kumra',            'মিষ্টি কুমড়া (সেদ্ধ)',                         'carb',     15, 2,  0, 2, 5,   350, 50,  'medium', ARRAY['vegetarian','ckd_restricted_high_k']::text[],                             '১ কাপ',                                    150, 'low_cost', true, 'easy',   'good'),
('c_potato_1pc',       'আলু সেদ্ধ (১টি মাঝারি)',                       'carb',     17, 2,  0, 2, 5,   420, 60,  'medium', ARRAY['vegetarian','ckd_restricted_high_k']::text[],                             '১টি ছোট (~৮০ গ্রাম)',                      80,  'low_cost', true, 'easy',   'neutral'),
('c_uguni',            'ভুনি (সুজি/সাগু)',                              'carb',     25, 3,  1, 2, 5,   30,  40,  'medium', ARRAY['low_sodium_ok','vegetarian']::text[],                                      '১ কাপ',                                    120, 'low_cost', true, 'medium', 'neutral')
on conflict (id) do nothing;

-- ---------- protein ----------
insert into public.foods (id, name_bn, category, carb_g, protein_g, fat_g, fiber_g, sodium_mg, potassium_mg, phosphorus_mg, gi_category, tags, portion_label, portion_g, affordability, common_in_bd, effort, healthiness) values
('p_rui',              'রুই মাছ ভাপা/ভুকরা (~৮০ গ্রাম)',                 'protein',  0,  18, 3,  0, 70,  280, 220, 'low',    ARRAY['low_sodium_ok','heart_moderate']::text[],                                '~৮০ গ্রাম',                                80,  'medium', true, 'medium', 'good'),
('p_tilapia',          'তেলাপিয়া মাছ (ভাপা/ভুকরা ~৮০ গ্রাম)',          'protein',  0,  17, 2,  0, 65,  260, 200, 'low',    ARRAY['low_sodium_ok','heart_moderate']::text[],                                '~৮০ গ্রাম',                                80,  'low_cost',true, 'medium', 'good'),
('p_katla',            'কাতলা মাছ (ভুকরা ~৮০ গ্রাম)',                  'protein',  0,  18, 4,  0, 60,  290, 210, 'low',    ARRAY['low_sodium_ok','heart_moderate']::text[],                                '~৮০ গ্রাম',                                80,  'medium', true, 'medium', 'good'),
('p_shing',            'শিং মাছ (ভুকরা ~৭০ গ্রাম)',                     'protein',  0,  19, 2,  0, 75,  300, 230, 'low',    ARRAY['low_sodium_ok','heart_moderate']::text[],                                '~৭০ গ্রাম',                                70,  'medium', true, 'medium', 'good'),
('p_murgi',            'মুরগির মাংস (চামড়া ছাড়া)',                    'protein',  0,  24, 5,  0, 160, 260, 190, 'low',    ARRAY['ckd_restricted_high_phos','low_sodium_ok','heart_moderate']::text[],     '২ টুকরা (~৯০ গ্রাম)',                      90,  'medium', true, 'medium', 'good'),
('p_deshi_murgi',      'দেশি মুরগি',                                   'protein',  0,  23, 6,  0, 165, 270, 195, 'low',    ARRAY['ckd_restricted_high_phos','low_sodium_ok','heart_moderate']::text[],     '২ টুকরা (~৮৫ গ্রাম)',                      85,  'medium', true, 'medium', 'good'),
('p_sola',             'সোল মাছ (শুকনো)',                              'protein',  0,  22, 2,  0, 380, 250, 150, 'low',    ARRAY['low_sodium_bad','ckd_restricted_high_phos']::text[],                     '২ টুকরা (~৩০ গ্রাম)',                      30,  'low_cost',true, 'easy',   'neutral'),
('p_dim',              'ডিম',                                          'protein',  2,  13, 10, 0, 190, 140, 180, 'low',    ARRAY['ckd_restricted_high_phos','heart_moderate','vegetarian_egg']::text[],     '১টি ডিম',                                  50,  'low_cost',true, 'easy',   'good'),
('p_moshur_dal',       'মসুর ডাল (ঘন)',                                'protein',  15, 9,  2,  5, 140, 250, 170, 'low',    ARRAY['ckd_restricted_high_phos','vegetarian','low_sodium_ok']::text[],          '১ বাটি (~১৫০ মিলি)',                      150, 'low_cost',true, 'easy',   'good'),
('p_mug_dal',          'মুগ ডাল (ঘন)',                                 'protein',  16, 10, 2,  5, 150, 260, 180, 'low',    ARRAY['ckd_restricted_high_phos','vegetarian','low_sodium_ok']::text[],          '১ বাটি',                                   150, 'low_cost',true, 'medium', 'good'),
('p_pabda',            'পাবদা মাছ (ঝোল)',                              'protein',  0,  17, 2,  0, 120, 240, 140, 'low',    ARRAY['vegetarian','low_sodium_ok']::text[],                                    '~৮০ গ্রাম',                                80,  'low_cost',true, 'easy',   'good'),
('p_liver',            'কলিজা (মুরগি)',                                 'protein',  5,  22, 6,  0, 110, 230, 350, 'low',    ARRAY['ckd_restricted_high_phos','low_sodium_ok']::text[],                      '১ টুকরা (~৭০ গ্রাম)',                      70,  'medium', true, 'medium', 'good')
on conflict (id) do nothing;

-- ---------- vegetables ----------
insert into public.foods (id, name_bn, category, carb_g, protein_g, fat_g, fiber_g, sodium_mg, potassium_mg, phosphorus_mg, gi_category, tags, portion_label, portion_g, affordability, common_in_bd, effort, healthiness) values
('v_lau',              'লাউ ভাজি',                                     'vegetable', 8, 2, 1, 3, 40, 130, 45, 'low', ARRAY['ckd_caution_moderate','vegetarian','low_sodium_ok']::text[],                  '১ বাটি',                                    100, 'low_cost', true, 'easy',   'good'),
('v_begun',            'বেগুন ভাজি',                                   'vegetable', 8, 2, 1, 3, 40, 130, 45, 'low', ARRAY['ckd_caution_moderate','vegetarian','low_sodium_ok']::text[],                  '১ বাটি',                                    100, 'low_cost', true, 'easy',   'good'),
('v_potol',            'পটল ভাজি',                                     'vegetable', 8, 2, 1, 3, 40, 130, 45, 'low', ARRAY['ckd_caution_moderate','vegetarian','low_sodium_ok']::text[],                  '১ বাটি',                                    100, 'low_cost', true, 'easy',   'good'),
('v_dhundul',          'ঢেঁড়স ভাজি',                                   'vegetable', 8, 2, 1, 3, 40, 130, 45, 'low', ARRAY['ckd_caution_moderate','vegetarian','low_sodium_ok']::text[],                  '১ বাটি',                                    100, 'low_cost', true, 'easy',   'good'),
('v_borboti',          'বরবটি ভাজি',                                   'vegetable', 8, 2, 1, 3, 40, 130, 45, 'low', ARRAY['ckd_caution_moderate','vegetarian','low_sodium_ok']::text[],                  '১ বাটি',                                    100, 'low_cost', true, 'easy',   'good'),
('v_lal_shak',         'লাল শাক',                                       'vegetable', 8, 2, 1, 3, 40, 180, 45, 'low', ARRAY['ckd_restricted_high_k','vegetarian','low_sodium_ok']::text[],                  '১ বাটি',                                    100, 'low_cost', true, 'easy',   'good'),
('v_palang_shak',      'পালং শাক',                                      'vegetable', 8, 2, 1, 3, 40, 180, 45, 'low', ARRAY['ckd_restricted_high_k','vegetarian','low_sodium_ok']::text[],                  '১ বাটি',                                    100, 'low_cost', true, 'easy',   'good'),
('v_kochu_shak',       'কচু শাক',                                      'vegetable', 8, 2, 1, 3, 40, 180, 45, 'low', ARRAY['ckd_restricted_high_k','vegetarian','low_sodium_ok']::text[],                  '১ বাটি',                                    100, 'low_cost', true, 'easy',   'good'),
('v_kolmi',            'কলমি শাক',                                     'vegetable', 8, 2, 1, 3, 40, 130, 45, 'low', ARRAY['ckd_caution_moderate','vegetarian','low_sodium_ok']::text[],                  '১ বাটি',                                    100, 'low_cost', true, 'easy',   'good'),
('v_korola',           'করলা ভাজি',                                    'vegetable', 8, 2, 1, 3, 40, 130, 45, 'low', ARRAY['ckd_caution_moderate','vegetarian','low_sodium_ok']::text[],                  '১ বাটি',                                    100, 'low_cost', true, 'medium', 'good'),
('v_chichinga',        'চিচিঙ্গা ভাজি',                                'vegetable', 8, 2, 1, 3, 40, 130, 45, 'low', ARRAY['ckd_caution_moderate','vegetarian','low_sodium_ok']::text[],                  '১ বাটি',                                    100, 'low_cost', true, 'easy',   'good'),
('v_shajna',           'শজনে ডাটা',                                    'vegetable', 8, 2, 1, 3, 40, 130, 45, 'low', ARRAY['ckd_caution_moderate','vegetarian','low_sodium_ok']::text[],                  '১ বাটি',                                    100, 'low_cost', true, 'easy',   'good'),
('v_bandhakopi',       'বাধাকপি ভাজি',                                  'vegetable', 8, 2, 1, 3, 40, 130, 45, 'low', ARRAY['ckd_caution_moderate','vegetarian','low_sodium_ok']::text[],                  '১ বাটি',                                    100, 'low_cost', true, 'easy',   'good'),
('v_kancha_morich',    'কাঁচা মরিচ + সবজি',                            'vegetable', 8, 2, 1, 3, 40, 130, 45, 'low', ARRAY['ckd_caution_moderate','vegetarian','low_sodium_ok']::text[],                  '১ বাটি',                                    100, 'low_cost', true, 'easy',   'good')
on conflict (id) do nothing;

-- ---------- dal ----------
insert into public.foods (id, name_bn, category, carb_g, protein_g, fat_g, fiber_g, sodium_mg, potassium_mg, phosphorus_mg, gi_category, tags, portion_label, portion_g, affordability, common_in_bd, effort, healthiness) values
('d_moshur',           'মসুর ডাল',                                     'dal', 12, 7, 1, 4, 90, 210, 150, 'low', ARRAY['ckd_restricted_high_phos','vegetarian','low_sodium_ok']::text[], 'আধা বাটি', 100, 'low_cost', true, 'easy',   'good'),
('d_mug',              'মুগ ডাল',                                      'dal', 12, 7, 1, 4, 90, 210, 150, 'low', ARRAY['ckd_restricted_high_phos','vegetarian','low_sodium_ok']::text[], 'আধা বাটি', 100, 'low_cost', true, 'medium', 'good'),
('d_rola',             'ছোলার ডাল',                                    'dal', 12, 7, 1, 4, 90, 210, 150, 'low', ARRAY['ckd_restricted_high_phos','vegetarian','low_sodium_ok']::text[], 'আধা বাটি', 100, 'low_cost', true, 'easy',   'good')
on conflict (id) do nothing;

-- ---------- snacks ----------
insert into public.foods (id, name_bn, category, carb_g, protein_g, fat_g, fiber_g, sodium_mg, potassium_mg, phosphorus_mg, gi_category, tags, portion_label, portion_g, affordability, common_in_bd, effort, healthiness) values
('s_peyara',           'পেয়ারা',                                       'snack', 14, 1, 0, 5, 2, 417, 30,  'low',    ARRAY['ckd_restricted_high_k','vegetarian','low_sodium_ok']::text[], '১টি মাঝারি',                    80,  'low_cost', true, 'easy',   'neutral'),
('s_papaya',           'পেঁপে (পাকা)',                                 'snack', 11, 1, 0, 2, 2, 180, 15,  'low',    ARRAY['vegetarian','low_sodium_ok']::text[],                            '১ কাপ',                       100, 'low_cost', true, 'easy',   'good'),
('s_am',               'আম (ছোট টুকরা)',                               'snack', 15, 1, 0, 2, 1, 170, 12,  'medium', ARRAY['vegetarian','low_sodium_ok']::text[],                            '~১০০ গ্রাম',                  100, 'medium',  true, 'easy',   'neutral'),
('s_jambura',          'বাতাবি লেবু',                                  'snack', 10, 1, 0, 2, 1, 216, 17,  'low',    ARRAY['ckd_restricted_high_k','vegetarian','low_sodium_ok']::text[], '২-৩ কোয়া',                    80,  'low_cost', true, 'easy',   'good'),
('s_dalim',            'ডালিম (বীজ)',                                  'snack', 13, 1, 0, 2, 2, 200, 18,  'low',    ARRAY['vegetarian','low_sodium_ok']::text[],                            'আধা কাপ',                    80,  'medium',  true, 'easy',   'good'),
('s_doi',              'টক দই (চিনি ছাড়া)',                            'snack', 7,  4, 2, 0, 40, 155, 95,  'low',    ARRAY['ckd_caution_moderate','vegetarian','low_sodium_ok']::text[], 'আধা কাপ',                    100, 'low_cost', true, 'easy',   'good'),
('s_chira',            'চিড়া (শুকনো)',                                 'snack', 24, 2, 0, 1, 25, 50,  40,  'high',   ARRAY['vegetarian']::text[],                                            '১ কাপ',                       30,  'low_cost', true, 'easy',   'bad'),
('s_muri_chola',       'মুড়ি + ছোলা',                                  'snack', 22, 5, 2, 4, 140, 150, 90, 'high',   ARRAY['ckd_caution_moderate','vegetarian']::text[],                    '১ কাপ',                       120, 'low_cost', true, 'easy',   'bad'),
('s_badam',            'বাদাম (১ মুঠো)',                                'snack', 6,  6, 14, 3, 1, 200, 140, 'low',   ARRAY['ckd_restricted_high_phos','vegetarian','low_sodium_ok']::text[], '১ মুঠো (~২০ গ্রাম)',          20,  'medium',  true, 'easy',   'good'),
('s_cha_biskut',       'চা + ২টি বিস্কুট',                              'snack', 16, 2, 3, 2, 80, 60,  50,  'medium', ARRAY['ckd_caution_moderate','vegetarian','low_sodium_ok']::text[], '১ কাপ + ২টি বিস্কুট',         150, 'low_cost', true, 'easy',   'neutral'),
('s_dab',              'ডাবের পানি',                                   'snack', 9,  0, 0, 0, 25, 250, 5,   'medium', ARRAY['ckd_restricted_high_k','vegetarian','low_sodium_ok']::text[], '১ গ্লাস (~২০০ মিলি)',        200, 'low_cost', true, 'easy',   'good'),
('s_tetul',            'তেঁতুল',                                       'snack', 10, 1, 0, 2, 5, 180, 25,  'low',    ARRAY['vegetarian','low_sodium_ok']::text[],                            '১ টুকরা (~২০ গ্রাম)',          20,  'low_cost', true, 'easy',   'good'),
('s_sobji_sidho',      'সবজি সিদ্ধ (গাজর/শসা/টমেটো)',                  'snack', 8,  1, 0, 3, 15, 160, 30,  'low',    ARRAY['ckd_caution_moderate','vegetarian','low_sodium_ok']::text[], '১ বাটি',                       100, 'low_cost', true, 'easy',   'good'),
('s_khichuri_light',   'খিচুড়ি (সবজি দিয়ে)',                           'snack', 22, 5, 2, 3, 90, 160, 80,  'medium', ARRAY['vegetarian','low_sodium_ok']::text[],                            '১ বাটি',                       150, 'low_cost', true, 'medium', 'good'),
('s_apple',            'আপেল',                                         'snack', 14, 0, 0, 2, 1, 107, 11,  'low',    ARRAY['vegetarian','low_sodium_ok']::text[],                            '১টি ছোট',                    100, 'medium',  false,'easy',   'good'),
('s_kola',             'কলা (ছোট)',                                    'snack', 23, 1, 0, 2, 1, 358, 22,  'medium', ARRAY['ckd_restricted_high_k','vegetarian']::text[],                   '১টি ছোট',                    80,  'low_cost', true, 'easy',   'neutral')
on conflict (id) do nothing;