-- ============================================================
-- Amar Diet — Full workouts catalogue seed (v2)
-- Apply AFTER 13_workouts.sql.
--
-- This file is a complete re-seed of public.workouts using the
-- widened schema (sub_category, difficulty, sets, repetitions,
-- frequency_per_week, equipment flags, suitability flags,
-- video_url, instructions_bn, safety_notes_bn, contraindications).
--
-- It uses on conflict (id) do update so it is safe to re-run.
-- Existing rows are refreshed in place; new rows are inserted.
-- ============================================================

insert into public.workouts (
  id, name_bn, name_en,
  category, sub_category, intensity, difficulty,
  duration_min, target_duration_seconds,
  sets, repetitions, frequency_per_week,
  target_calories_kcal,
  description_bn, instructions_bn,
  equipment,
  beginner, elderly_friendly, chair_supported, low_impact,
  joint_friendly, balance_required,
  diabetes_suitable, hypertension_suitable, obesity_suitable, anemia_suitable,
  video_url,
  safety_notes_bn, contraindications
) values

-- ============================================================
-- 1. AEROBIC EXERCISES (cardio / walking)
-- ============================================================
('aero_slow_walk',     'ধীর হাঁটা',              'Slow walking',
 'walking','aerobic','low','beginner',
 30,1800, NULL,NULL,7,
 25,
 'স্বাভাবিক গতিতে হাঁটা — শরীর গরম করা ও হার্টের জন্য ভালো।',
 'একটানা ২০-৩০ মিনিট হাঁটুন। ফোনে কথা বলার সময়ও হাঁটতে পারেন।',
 '{}'::text[],
 true,true,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'হাঁটার আগে ২-৩ মিনিট আলগা গতিতে শুরু করুন। পিপাসা লাগলে পানি পান করুন।',
 'খালি পেটে বা ইনসুলিনের পিক-এ সময় এড়িয়ে চলুন।'),

('aero_normal_walk',   'স্বাভাবিক হাঁটা',         'Normal walking',
 'walking','aerobic','low','beginner',
 30,1800, NULL,NULL,7,
 30,
 'প্রতিদিনের স্বাভাবিক হাঁটা — কাজের ফাঁকে বা সন্ধ্যায়।',
 '৩০ মিনিট একটানা হাঁটুন, কাঁধ শিথিল রাখুন।',
 '{}'::text[],
 true,true,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'হাঁটার পর ৫ মিনিট ধীরে ধীরে গতি কমিয়ে শেষ করুন।',
 NULL),

('aero_brisk_walk',    'দ্রুত হাঁটা',             'Brisk walking',
 'walking','aerobic','medium','intermediate',
 40,2400, NULL,NULL,5,
 45,
 'একটু দ্রুত গতিতে হাঁটা — রক্তে শর্করা নিয়ন্ত্রণে সবচেয়ে কার্যকর।',
 'গতি এমন হওয়া উচিত যেন কথা বলতে পারেন কিন্তু গান গাইতে না পারেন।',
 '{}'::text[],
 true,true,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'বুকে ব্যথা, মাথা ঘোরা বা অস্বস্তি হলে থামুন।',
 'আর্থ্রাইটিস তীব্র হলে ছোট ছোট সেশনে ভাগ করুন।'),

('aero_walk_in_place', 'জায়গায় হাঁটা',           'Walking in place',
 'walking','aerobic','low','beginner',
 20,1200, NULL,NULL,7,
 18,
 'ঘরের ভেতরে জায়গায় হেঁটে সারাদিন সক্রিয় থাকা।',
 'টিভি দেখার সময় বা ফোনে কথা বলার সময় জায়গায় হাঁটুন।',
 '{}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL,
 'হাঁটুর উপর বেশি চাপ পড়লে চেয়ারে বসে পা তুলুন।',
 NULL),

('aero_indoor_walk',   'ঘরে হাঁটা',              'Indoor walking',
 'walking','aerobic','low','beginner',
 30,1800, NULL,NULL,7,
 22,
 'বৃষ্টি বা গরমের দিনে ঘরের ভেতরে হেঁটে সক্রিয় থাকা।',
 'ঘরের এক প্রান্ত থেকে আরেক প্রান্তে পায়চারি করুন।',
 '{}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL,
 'পিছল-মুক্ত মেঝে নিশ্চিত করুন।',
 NULL),

('aero_stair_walk',    'সিঁড়ি ওঠা',             'Stair walking',
 'cardio','aerobic','medium','intermediate',
 15,900, NULL,NULL,4,
 40,
 'সিঁড়ি দিয়ে ওঠানামা — পায়ের পেশি ও হার্ট দুটোই শক্তিশালী হয়।',
 '২-৩ তলা ওঠে নেমে আসুন, ৩-৫ বার পুনরাবৃত্তি করুন।',
 '{}'::text[],
 false,false,false,false,
 true,true,
 true,false,false,false,
 NULL,
 'হ্যান্ডরেল ধরে ওঠুন। হাঁপিয়ে গেলে থামুন।',
 'হাঁটু বা কোমরে ব্যথা, উচ্চ রক্তচাপ নিয়ন্ত্রণে না থাকলে এড়িয়ে চলুন।'),

('aero_cycling',       'সাইকেল চালানো',         'Cycling',
 'cardio','aerobic','medium','intermediate',
 45,2700, NULL,NULL,4,
 50,
 'বাইরে সাইকেল চালানো — হাঁটুর ওপর কম চাপ পড়ে।',
 'সমতল রাস্তায় ৩০-৪৫ মিনিট চালান। হেলমেট পরুন।',
 '{"bicycle"}'::text[],
 false,false,false,true,
 true,true,
 true,true,true,false,
 NULL,
 'ট্রাফিক-সচেতন থাকুন। পানি সাথে রাখুন।',
 'অস্থির রক্তচাপ বা হৃদরোগ থাকলে ডাক্তারের পরামর্শ নিন।'),

('aero_stationary',    'স্থির সাইকেল',           'Stationary cycling',
 'cardio','aerobic','low','beginner',
 40,2400, NULL,NULL,4,
 35,
 'ঘরে স্থির সাইকেল চালানো — আবহাওয়া নির্বিশেষে ব্যায়াম।',
 'প্রতি ৫ মিনিটে রেজিস্ট্যান্স বাড়ান, শেষে আবার কমান।',
 '{"stationary_bike"}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL,
 'বসার উচ্চতা এমন হওয়া উচিত যেন পা সম্পূর্ণ প্রসারিত হলে হাঁটু একটু বাঁকা থাকে।',
 'রক্তচাপ খুব বেশি বা কম থাকলে এড়িয়ে চলুন।'),

('aero_swim',          'সাঁতার',                'Swimming',
 'cardio','aerobic','medium','intermediate',
 40,2400, NULL,NULL,3,
 55,
 'পুকুর বা সুইমিং পুলে সাঁতার কাটা — সারা শরীরের ব্যায়াম।',
 'ফ্রি-স্টাইলে ২০-৪০ মিনিট। ৫ মিনিট বিশ্রাম নিয়ে সেট ভাগ করুন।',
 '{"pool"}'::text[],
 false,false,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'একা সাঁতার এড়িয়ে চলুন। শেখানো প্রশিক্ষক তত্ত্বাবধানে শুরু করুন।',
 'ক্লোরিন অ্যালার্জি, কানের সংক্রমণ, খোলা ক্ষত থাকলে সাঁতার এড়িয়ে চলুন।'),

('aero_water_walk',    'পানিতে হাঁটা',          'Water walking',
 'cardio','aerobic','medium','beginner',
 30,1800, NULL,NULL,3,
 45,
 'বুক-পানি পর্যন্ত গভীরে হেঁটে জয়েন্ট-ফ্রেন্ডলি কার্ডিও।',
 'পুকুরে বা পুলে ২০-৩০ মিনিট হাঁটুন।',
 '{"pool"}'::text[],
 true,true,false,true,
 true,true,
 true,true,true,false,
 NULL,
 'পিছল-মুক্ত পুলের তলা ব্যবহার করুন।',
 'হৃদরোগ গুরুতর হলে ডাক্তারের পরামর্শ নিন।'),

('aero_dance',         'নাচ',                  'Dancing',
 'cardio','aerobic','medium','intermediate',
 30,1800, NULL,NULL,4,
 35,
 'বাড়িতে বা সামাজিকভাবে নাচ — মজা পেতে পেতে কার্ডিও।',
 'আপনার পছন্দের গানে ২০-৩০ মিনিট নাচুন।',
 '{}'::text[],
 true,false,false,true,
 true,true,
 true,true,true,true,
 NULL,
 'জুতো ঢিলেঢালা ও পিছল-মুক্ত রাখুন।',
 'হাঁটুর তীব্র ব্যথা থাকলে এড়িয়ে চলুন।'),

('aero_light_aero',    'হালকা অ্যারোবিক্স',     'Light aerobics',
 'cardio','aerobic','medium','beginner',
 30,1800, NULL,NULL,4,
 32,
 'ঘরে সহজ অ্যারোবিক্স রুটিন — ক্লাস ছাড়াই।',
 'ওয়ার্ম-আপ ৫ মিনিট → ২০ মিনিট স্টেপ/জাম্প → কুল-ডাউন ৫ মিনিট।',
 '{}'::text[],
 true,false,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'জাম্পিং করলে নরম মেঝে ব্যবহার করুন।',
 'জয়েন্ট ব্যথা থাকলে লো-ইমপ্যাক্ট ভ্যারিয়েশন বেছে নিন।'),

('aero_low_impact',    'লো-ইমপ্যাক্ট অ্যারোবিক্স','Low-impact aerobics',
 'cardio','aerobic','low','beginner',
 30,1800, NULL,NULL,4,
 28,
 'জাম্পিং ছাড়া অ্যারোবিক্স — জয়েন্ট-ফ্রেন্ডলি।',
 'এক পায়ের বদলে অন্য পায়ে ওজন স্থানান্তর করুন।',
 '{}'::text[],
 true,true,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'ধীরে শুরু করুন, ২ সপ্তাহে ছন্দে আসবেন।',
 NULL),

('aero_light_jog',     'হালকা জগিং',           'Light jogging',
 'cardio','aerobic','high','intermediate',
 30,1800, NULL,NULL,3,
 50,
 'ধীরে ছোট দৌড় — ফিটনেস ভালো হলে শুরু করুন।',
 '৫ মিনিট হাঁটা → ১০ মিনিট জগিং → ৫ মিনিট হাঁটা।',
 '{}'::text[],
 false,false,false,false,
 false,true,
 true,false,true,false,
 NULL,
 'জগিং করার আগে ওয়ার্ম-আপ অবশ্যই করুন।',
 'হাঁটু/গোড়ালির ব্যথা, ওজন বেশি বা অনিয়ন্ত্রিত রক্তচাপ থাকলে এড়িয়ে চলুন।'),

('aero_jog_walk',      'জগ-ওয়াক ইন্টারভাল',   'Jog-walk intervals',
 'cardio','aerobic','medium','intermediate',
 30,1800, NULL,NULL,4,
 45,
 'জগ ও ওয়াকের পালাক্রম — কার্যকর ও সহজ শুরু।',
 '১ মিনিট জগ → ২ মিনিট হাঁটা, ১০ বার পুনরাবৃত্তি।',
 '{}'::text[],
 true,false,false,false,
 true,true,
 true,true,true,true,
 NULL,
 'মাথা ঘোরা বা অস্বস্তি হলে থামুন।',
 'হৃদরোগ গুরুতর হলে ডাক্তারের পরামর্শ নিন।'),

('aero_rowing',        'রোয়িং মেশিন',          'Rowing machine',
 'cardio','aerobic','medium','intermediate',
 30,1800, NULL,NULL,3,
 55,
 'রোয়িং মেশিনে টানা — পুরো শরীরের ব্যায়াম।',
 '৫ মিনিট ওয়ার্ম-আপ → ২০ মিনিট স্টেডি → ৫ মিনিট কুল-ডাউন।',
 '{"rowing_machine"}'::text[],
 false,false,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'পিঠে ব্যথা হলে ছোট সেশনে ভাগ করুন।',
 'পিঠের তীব্র ব্যথা বা হার্নিয়া থাকলে এড়িয়ে চলুন।'),

-- ============================================================
-- 2. STRENGTH / RESISTANCE
-- ============================================================
('str_sit_to_stand',   'বসা-থেকে-ওঠা',          'Sit-to-stand',
 'strength','lower_body','low','beginner',
 12,720, 2,'10-15',3,
 20,
 'চেয়ার থেকে উঠে আবার বসা — পায়ের পেশি শক্তিশালী করে।',
 'চেয়ারের সামনে দাঁড়ান, ধীরে নেমে প্রায় বসুন, আবার উঠুন। ১০-১৫ বার × ২-৩ সেট।',
 '{"chair"}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL,
 'হাঁটু ব্যথা হলে উচ্চতর চেয়ার ব্যবহার করুন।',
 NULL),

('str_chair_squat',    'চেয়ার স্কোয়াট',         'Chair squat',
 'strength','lower_body','low','beginner',
 12,720, 2,'10-15',3,
 22,
 'চেয়ারের সামনে স্কোয়াট — বাট, কোয়াড্রিসেপস ও হ্যামস্ট্রিং।',
 'পা কাঁধ-সমান ফাঁক, পিঠ সোজা, ধীরে নেমে মাথা ছোঁয়ার আগে থামুন।',
 '{"chair"}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL,
 'হাঁটু সামনে ভাঁজ হলে ভুল — পায়ের ওপর ওজন রাখুন।',
 'হাঁটুর তীব্র ব্যথা থাকলে ওয়াল সিট করুন।'),

('str_bodyweight_squat','বডি-ওয়েট স্কোয়াট',   'Bodyweight squat',
 'strength','lower_body','medium','intermediate',
 12,720, 2,'10-15',3,
 28,
 'চেয়ার ছাড়া পূর্ণ স্কোয়াট।',
 'নিতম্ব পেছনে ঠেলে নামুন, হাঁটু গোড়ালির ওপর রাখুন।',
 '{}'::text[],
 false,false,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'পিঠ সোজা রাখুন, হাঁটু ভেতরে পড়লে ভুল।',
 NULL),

('str_wall_pushup',    'দেয়ালে পুশআপ',         'Wall push-up',
 'strength','upper_body','low','beginner',
 10,600, 2,'10-15',3,
 15,
 'দেয়ালে হাত রেখে পুশআপ — বুক ও ট্রাইসেপস।',
 'হাত কাঁধ-সমান উচ্চতায়, দেহ সোজা রেখে বুক দেয়ালের কাছে আনুন।',
 '{}'::text[],
 true,true,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'কাঁধ ব্যথা হলে কম রেঞ্জে করুন।',
 'কাঁধের তীব্র ব্যথা থাকলে এড়িয়ে চলুন।'),

('str_incline_pushup', 'ইনক্লাইন পুশআপ',      'Incline push-up',
 'strength','upper_body','medium','intermediate',
 10,600, 2,'8-12',3,
 20,
 'টেবিল বা বেঞ্চে হাত রেখে পুশআপ।',
 'বেঞ্চের উচ্চতা কমিয়ে কঠিন করুন।',
 '{}'::text[],
 false,false,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'কোর টাইট রাখুন, পিঠ নিচু করবেন না।',
 NULL),

('str_band_row',       'রেজিস্ট্যান্স ব্যান্ড রো','Resistance-band row',
 'strength','upper_body','medium','intermediate',
 10,600, 2,'10-15',3,
 22,
 'ব্যান্ড টেনে রো — পিঠের মাংসপেশি।',
 'পা ব্যান্ডের ওপর রাখুন, পিঠ সোজা, কনুই পেছনে টানুন।',
 '{"resistance_band"}'::text[],
 false,false,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'কাঁধ শিথিল, ঘাড়ে টান দেবেন না।',
 'কাঁধের তীব্র সমস্যা থাকলে এড়িয়ে চলুন।'),

('str_band_chest',     'ব্যান্ড চেস্ট প্রেস',   'Resistance-band chest press',
 'strength','upper_body','medium','intermediate',
 10,600, 2,'10-15',3,
 20,
 'ব্যান্ড সামনে থেকে ছেড়ে দেওয়া — চেস্ট ও ট্রাইসেপস।',
 'ব্যান্ড পিঠের পেছনে, দুই হাত দিয়ে সামনে ঠেলুন।',
 '{"resistance_band"}'::text[],
 false,false,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'কনুই শরীরের কাছে রাখুন।',
 NULL),

('str_biceps_curl',    'বাইসেপস কার্ল',         'Biceps curl',
 'strength','upper_body','low','beginner',
 10,600, 2,'10-15',3,
 18,
 'হাতের ওজন তুলে কার্ল — বাইসেপস।',
 'কনুই শরীরের পাশে আটকে, হাত ধীরে ওঠান ও নামান।',
 '{"dumbbell"}'::text[],
 true,true,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'ওজন বেশি হলে কাঁধে টান পড়ে — হালকা দিয়ে শুরু করুন।',
 NULL),

('str_triceps_ext',    'ট্রাইসেপস এক্সটেনশন', 'Triceps extension',
 'strength','upper_body','low','beginner',
 10,600, 2,'10-15',3,
 18,
 'মাথার ওপরে হাত তুলে এক্সটেনশন — ট্রাইসেপস।',
 'মাথার পেছনে হাত নামিয়ে আবার ওপরে তুলুন।',
 '{"dumbbell"}'::text[],
 true,true,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'কনুই স্থির রাখুন, কাঁধ নড়াবেন না।',
 'কনুই ব্যথা থাকলে এড়িয়ে চলুন।'),

('str_shoulder_press', 'শোল্ডার প্রেস',         'Shoulder press',
 'strength','upper_body','medium','intermediate',
 10,600, 2,'8-12',3,
 22,
 'কাঁধের ওপরে ওজন তোলা — দেল্টয়েড ও ট্রাইসেপস।',
 'কাঁধ-সমান গ্রিপে কানের পাশ দিয়ে ওজন ওঠান।',
 '{"dumbbell"}'::text[],
 false,false,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'পিঠ চেয়ারে ঠেকিয়ে রাখুন।',
 'কাঁধে ব্যথা বা রোটেটর কাফ ইনজুরি থাকলে এড়িয়ে চলুন।'),

('str_lateral_raise',  'ল্যাটারাল রেইজ',        'Lateral raise',
 'strength','upper_body','low','beginner',
 8,480, 2,'10-15',3,
 15,
 'পাশে হাত তোলা — সাইড দেল্টয়েড।',
 'হাত একটু বাঁকা রেখে কাঁধ-সমান উচ্চতায় তুলুন।',
 '{"dumbbell"}'::text[],
 true,true,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'ঝাঁকি দিয়ে তুলবেন না — ধীরে ওঠান ও নামান।',
 NULL),

('str_calf_raise',     'কাফ রেইজ',             'Calf raise',
 'strength','lower_body','low','beginner',
 8,480, 2,'10-15',3,
 15,
 'গোড়ালি তুলে নামানো — পায়ের পেশি।',
 'চেয়ার/দেয়াল ধরে ধীরে ওঠান ও নামান।',
 '{"chair"}'::text[],
 true,true,true,true,
 true,true,
 true,true,true,true,
 NULL,
 'ব্যালেন্সের জন্য সাপোর্ট রাখুন।',
 NULL),

('str_glute_bridge',   'গ্লুট ব্রিজ',           'Glute bridge',
 'strength','lower_body','low','beginner',
 8,480, 2,'10-15',3,
 18,
 'শুয়ে নিতম্ব তোলা — গ্লুট ও হ্যামস্ট্রিং।',
 'হাঁটু ভাঁজ, পা মেঝেতে, নিতম্ব ওপরে তুলুন ৫ সেকেন্ড ধরে রাখুন।',
 '{}'::text[],
 true,true,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'পিঠ নিচু রাখুন, ধাক্কা দিয়ে তুলবেন না।',
 'পিঠের তীব্র ব্যথা থাকলে এড়িয়ে চলুন।'),

('str_step_up',        'স্টেপ-আপ',             'Step-up',
 'strength','lower_body','medium','intermediate',
 12,720, 2,'8-12',3,
 25,
 'একটি ধাপে ওঠা — পায়ের পেশি ও ব্যালেন্স।',
 'এক পা ধাপে, অন্য পা তুলুন, ধীরে নামুন। পা বদলান।',
 '{"step"}'::text[],
 false,false,false,true,
 true,true,
 true,true,true,true,
 NULL,
 'ধাপের উচ্চতা আপনার ক্ষমতা অনুযায়ী রাখুন।',
 'হাঁটু ব্যথা থাকলে এড়িয়ে চলুন।'),

('str_leg_extension',  'লেগ এক্সটেনশন',        'Leg extension',
 'strength','lower_body','low','beginner',
 8,480, 2,'10-15',3,
 16,
 'চেয়ারে বসে পা সোজা করা — কোয়াড্রিসেপস।',
 'ধীরে পা সোজা তুলুন, ৩ সেকেন্ড ধরে রাখুন, নামান।',
 '{"chair"}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL,
 'পিঠ চেয়ারে ঠেকিয়ে রাখুন।',
 NULL),

('str_hamstring_curl', 'হ্যামস্ট্রিং কার্ল',    'Hamstring curl',
 'strength','lower_body','low','beginner',
 8,480, 2,'10-15',3,
 16,
 'চেয়ারে বসে গোড়ালি পেছনে টানা — হ্যামস্ট্রিং।',
 'পায়ের পেছনে ব্যান্ড/ওজন রাখুন, গোড়ালি পেছনে বাঁকুন।',
 '{"resistance_band","chair"}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL,
 'হাঁটু এক জায়গায় রাখুন।',
 NULL),

('str_seated_leg_raise','বসে পা তোলা',         'Seated leg raise',
 'strength','lower_body','low','beginner',
 8,480, 2,'10-15',3,
 14,
 'চেয়ারে বসে এক পা সোজা তোলা — হিপ ফ্লেক্সর।',
 'এক পা ধীরে সোজা তুলুন, ৫ সেকেন্ড ধরে রাখুন, নামান।',
 '{"chair"}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL,
 'পিঠ চেয়ারে ঠেকানো থাকবে।',
 NULL),

('str_db_row',         'হালকা ডাম্বেল রো',     'Light dumbbell row',
 'strength','upper_body','medium','intermediate',
 10,600, 2,'8-12',3,
 20,
 'ডাম্বেল দিয়ে রো — পিঠ ও বাইসেপস।',
 'এক হাত ও এক হাঁটু বেঞ্চে, অন্য হাতে ডাম্বেল পাশে তুলুন।',
 '{"dumbbell","bench"}'::text[],
 false,false,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'পিঠ সমতল রাখুন, ঘাড়ে টান দেবেন না।',
 NULL),

('str_db_squat',       'হালকা ডাম্বেল স্কোয়াট','Light dumbbell squat',
 'strength','lower_body','medium','intermediate',
 12,720, 2,'8-12',3,
 25,
 'দুই হাতে ডাম্বেল ধরে স্কোয়াট।',
 'পা কাঁধ-সমান, হাতে হালকা ওজন, ধীরে নেমে আবার উঠুন।',
 '{"dumbbell"}'::text[],
 false,false,false,true,
 true,false,
 true,true,true,true,
 NULL,
 'হাঁটু গোড়ালির ওপর রাখুন।',
 NULL),

-- ============================================================
-- 3. FLEXIBILITY / STRETCHING
-- ============================================================
('flex_neck',          'ঘাড়ের স্ট্রেচ',         'Neck stretch',
 'flexibility','neck','low','beginner',
 3,180, NULL,'10-30 sec × 2',3,
 5,
 'ঘাড়ের পেশি শিথিল করা।',
 'মাথা ধীরে ডানে, ১৫ সেকেন্ড ধরে রাখুন, বামে একই।',
 '{}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL,
 'ঘাড় ঘোরানো এড়িয়ে চলুন — শুধু কাত করুন।',
 'ঘাড়ে হঠাৎ ব্যথা বা মাথা ঘোরা হলে বন্ধ করুন।'),

('flex_shoulder',      'কাঁধের স্ট্রেচ',        'Shoulder stretch',
 'flexibility','upper_body','low','beginner',
 3,180, NULL,'10-30 sec × 2',3,
 5,
 'কাঁধের পেশি শিথিল করা।',
 'এক হাত বুকের ওপর দিয়ে, অন্য হাতে কনুই টানুন।',
 '{}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL,
 'ধীরে টানুন, ঝাঁকি দেবেন না।',
 NULL),

('flex_shoulder_roll', 'শোল্ডার রোল',          'Shoulder roll',
 'flexibility','upper_body','low','beginner',
 3,180, NULL,'10-15 reps',3,
 6,
 'কাঁধ ঘুরিয়ে আঁটসাঁট ভাব কমানো।',
 'সামনে ১০ বার বড় বৃত্ত, পেছনে ১০ বার।',
 '{}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('flex_arm_cross',     'আর্ম ক্রস-বডি স্ট্রেচ','Arm cross-body stretch',
 'flexibility','upper_body','low','beginner',
 3,180, NULL,'10-30 sec × 2',3,
 5,
 'কাঁধের পেছনের পেশি টানা।',
 'এক হাত সোজা বুকের ওপর দিয়ে, অন্য হাতে কনুই টানুন।',
 '{}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('flex_chest',         'চেস্ট স্ট্রেচ',        'Chest stretch',
 'flexibility','upper_body','low','beginner',
 3,180, NULL,'10-30 sec × 2',3,
 5,
 'বুকের পেশি প্রসারিত করা।',
 'দরজার ফ্রেমে দুই হাত রেখে সামনে এক পা রাখুন, ধীরে ঝুঁকুন।',
 '{}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('flex_upper_back',    'আপার-ব্যাক স্ট্রেচ',  'Upper-back stretch',
 'flexibility','upper_body','low','beginner',
 3,180, NULL,'10-30 sec × 2',3,
 5,
 'পিঠের ওপরের অংশ শিথিল করা।',
 'দুই হাত সামনে প্রসারিত, পিঠ গোল করে কাঁধ সামনে আনুন।',
 '{}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('flex_side',          'সাইড স্ট্রেচ',         'Side stretch',
 'flexibility','core','low','beginner',
 3,180, NULL,'10-30 sec × 2',3,
 6,
 'পাশের পেশি টানা।',
 'এক হাত মাথার ওপর, অন্য দিকে ধীরে ঝুঁকুন।',
 '{}'::text[],
 true,true,true,true,
 true,true,
 true,true,true,true,
 NULL, NULL, NULL),

('flex_hip',           'হিপ স্ট্রেচ',          'Hip stretch',
 'flexibility','lower_body','low','beginner',
 4,240, NULL,'10-30 sec × 2',3,
 7,
 'নিতম্বের পেশি শিথিল করা।',
 'এক পা টেবিলের ওপর রাখুন, শরীর সামনে ঝুঁকুন।',
 '{}'::text[],
 true,true,false,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('flex_hamstring',     'হ্যামস্ট্রিং স্ট্রেচ', 'Hamstring stretch',
 'flexibility','lower_body','low','beginner',
 4,240, NULL,'10-30 sec × 2',3,
 7,
 'পায়ের পেছনের পেশি টানা।',
 'দাঁড়িয়ে এক পা সামনে, গোড়ালি ওপরে টানুন।',
 '{}'::text[],
 true,true,false,true,
 true,false,
 true,true,true,true,
 NULL, NULL,
 'হ্যামস্ট্রিং টিয়ার থাকলে গভীর টান এড়িয়ে চলুন।'),

('flex_quad',          'কোয়াড্রিসেপস স্ট্রেচ','Quadriceps stretch',
 'flexibility','lower_body','low','beginner',
 4,240, NULL,'10-30 sec × 2',3,
 7,
 'পায়ের সামনের পেশি টানা।',
 'দাঁড়িয়ে গোড়ালি পেছনে ধরে নিতম্বের কাছে আনুন।',
 '{"chair"}'::text[],
 true,true,false,true,
 true,true,
 true,true,true,true,
 NULL, NULL, NULL),

('flex_calf',          'কাফ স্ট্রেচ',          'Calf stretch',
 'flexibility','lower_body','low','beginner',
 4,240, NULL,'10-30 sec × 2',3,
 6,
 'গোড়ালির পেশি টানা।',
 'দেয়ালে হাত রেখে এক পা পেছনে, গোড়ালি মেঝেতে চেপে ধরুন।',
 '{}'::text[],
 true,true,false,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('flex_ankle_circle',  'গোড়ালি ঘোরানো',       'Ankle circles',
 'flexibility','lower_body','low','beginner',
 3,180, NULL,'10-15 reps',3,
 5,
 'গোড়ালির জয়েন্ট মোবাইল রাখা।',
 'এক পা তুলে গোড়ালি ধীরে ঘোরান, দিক বদলান।',
 '{"chair"}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('flex_full_body',     'সারা শরীর স্ট্রেচ',   'Full-body gentle stretching',
 'flexibility','full_body','low','beginner',
 15,900, NULL,'15-30 sec each',7,
 15,
 'মাথা থেকে পা — পুরো শরীরের হালকা স্ট্রেচিং।',
 'ঘাড়→কাঁধ→বাহু→কোমর→পায়ের স্ট্রেচ, প্রতিটি ১৫-৩০ সেকেন্ড।',
 '{}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL,
 'স্ট্রেচের সময় শ্বাস ছাড়ুন, ধরে রাখলে শ্বাস নিন।',
 NULL),

-- ============================================================
-- 4. BALANCE EXERCISES
-- ============================================================
('bal_single_leg',     'এক-পায়ে দাঁড়ানো',     'Supported single-leg stand',
 'balance','static','low','beginner',
 5,300, NULL,'10-30 sec',5,
 6,
 'এক পায়ে ভারসাম্য রাখা — পতন প্রতিরোধ।',
 'চেয়ার/দেয়ালের কাছে দাঁড়ান, এক পা তুলুন, ১০-৩০ সেকেন্ড ধরে রাখুন।',
 '{"chair"}'::text[],
 true,true,true,true,
 true,true,
 true,true,true,true,
 NULL,
 'সবসময় সাপোর্টের কাছে থাকুন।',
 'গুরুতর অস্টিওপোরোসিস বা পতন-ইতিহাস থাকলে শুধু সাপোর্টসহ করুন।'),

('bal_heel_toe',       'হিল-টু-টো ওয়াক',     'Heel-to-toe walk',
 'balance','dynamic','low','beginner',
 10,600, NULL,'5-10 min',5,
 12,
 'একটি সরল রেখায় গোড়ালি-পায়ের আঙুল গোড়ালি-পায়ের আঙুল রেখে হাঁটা।',
 'দেয়ালের পাশে ৫-১০ মিনিট ধরে এই ভঙ্গিতে হাঁটুন।',
 '{}'::text[],
 true,false,false,true,
 true,true,
 true,true,true,true,
 NULL,
 'সাপোর্টের কাছে থাকুন। টালি/বিছানার ধারে অনুশীলন করুন।',
 'পতন-ভীতি বেশি হলে প্রথমে চেয়ারের পাশে রাখুন।'),

('bal_sideways',       'পাশাপাশি হাঁটা',      'Sideways walking',
 'balance','dynamic','low','beginner',
 10,600, NULL,'5-10 min',5,
 12,
 'পাশের দিকে পা-পাশাপাশি সরিয়ে হাঁটা — হিপ অ্যাবডাক্টর।',
 'প্রতি দিকে ১০ পা, ৩-৫ বার পুনরাবৃত্তি।',
 '{}'::text[],
 true,true,false,true,
 true,true,
 true,true,true,true,
 NULL, NULL, NULL),

('bal_heel_raise',     'হিল রেইজ',             'Heel raises',
 'balance','lower_body','low','beginner',
 6,360, 2,'10-15',5,
 12,
 'গোড়ালি তুলে হিল-রেইজ — ব্যালেন্স ও গোড়ালির পেশি।',
 'চেয়ার/দেয়াল ধরে, ১০-১৫ বার × ২-৩ সেট।',
 '{"chair"}'::text[],
 true,true,true,true,
 true,true,
 true,true,true,true,
 NULL, NULL, NULL),

('bal_toe_raise',      'টো রেইজ',              'Toe raises',
 'balance','lower_body','low','beginner',
 6,360, 2,'10-15',5,
 12,
 'আঙুলের ওপর ভর দিয়ে ওঠা — শিন ও ব্যালেন্স।',
 'চেয়ার/দেয়াল ধরে, ধীরে ওঠান ও নামান।',
 '{"chair"}'::text[],
 true,true,true,true,
 true,true,
 true,true,true,true,
 NULL, NULL, NULL),

('bal_sit_stand',      'বসা-ওঠা ব্যালেন্স',    'Sit-to-stand (balance)',
 'balance','functional','low','beginner',
 8,480, 2,'10-15',5,
 16,
 'চেয়ার থেকে ওঠার ব্যায়াম — ব্যালেন্স ও পায়ের শক্তি একসাথে।',
 'চেয়ারের সামনে দাঁড়ান, ধীরে নেমে প্রায় বসুন, ব্যালেন্স রেখে উঠুন।',
 '{"chair"}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('bal_step_over',      'স্টেপ-ওভার',          'Step-over practice',
 'balance','dynamic','medium','intermediate',
 10,600, NULL,'5-10 min',3,
 15,
 'বস্তুর ওপর দিয়ে পা তুলে হাঁটা — গেট ও ব্যালেন্স।',
 '১০-১৫ সেমি উঁচু বস্তুর ওপর দিয়ে ৫-১০ মিনিট হাঁটুন।',
 '{}'::text[],
 false,false,false,true,
 true,true,
 true,true,true,true,
 NULL, NULL,
 'পতন-ঝুঁকি বেশি হলে এড়িয়ে চলুন।'),

('bal_tandem',         'ট্যান্ডেম স্ট্যান্স', 'Tandem stance',
 'balance','static','low','beginner',
 5,300, NULL,'20-30 sec',5,
 6,
 'এক পায়ের গোড়ালি অন্য পায়ের আঙুলের কাছে রেখে দাঁড়ানো।',
 'সাপোর্টের কাছে ২০-৩০ সেকেন্ড দাঁড়ান।',
 '{"chair"}'::text[],
 true,true,true,true,
 true,true,
 true,true,true,true,
 NULL, NULL, NULL),

('bal_weight_shift',   'ওজন স্থানান্তর',      'Weight shifting',
 'balance','dynamic','low','beginner',
 10,600, NULL,'5-10 min',5,
 10,
 'ডান-বামে ওজন স্থানান্তর — গেট ও অ্যাঙ্কেল কন্ট্রোল।',
 'সোজা দাঁড়ান, ৫-১০ সেকেন্ড এক পায়ে ওজন রাখুন, বদলান।',
 '{}'::text[],
 true,true,true,true,
 true,true,
 true,true,true,true,
 NULL, NULL, NULL),

('bal_chair_balance',  'চেয়ার-সাপোর্টেড ব্যালেন্স','Chair-supported balance',
 'balance','static','low','beginner',
 10,600, NULL,'10 min',5,
 10,
 'চেয়ারের পেছনে হালকাভাবে ধরে বিভিন্ন ব্যালেন্স অনুশীলন।',
 'এক-পায়ে দাঁড়ানো, গোড়ালি তোলা, ট্যান্ডেম — ১০ মিনিট।',
 '{"chair"}'::text[],
 true,true,true,true,
 true,true,
 true,true,true,true,
 NULL, NULL, NULL),

-- ============================================================
-- 5. YOGA / GENTLE MOVEMENT
-- ============================================================
('yoga_gentle',        'হালকা যোগা',          'Gentle yoga',
 'yoga','full_body','low','beginner',
 20,1200, NULL,'15-20 min',3,
 25,
 'সহজ যোগা সিকোয়েন্স — নমনীয়তা ও শান্তি।',
 'ওয়ার্ম-আপ → স্ট্যান্ডিং পোজ → ম্যাট পোজ → সাভাসনা।',
 '{"mat"}'::text[],
 true,false,true,true,
 true,true,
 true,true,true,true,
 NULL,
 'খালি পেটে করুন বা ২ ঘণ্টা পর করুন।',
 'গুরুতর আর্থ্রাইটিস বা হার্নিয়া থাকলে পোজ মডিফাই করুন।'),

('yoga_chair',         'চেয়ার যোগা',          'Chair yoga',
 'yoga','full_body','low','beginner',
 20,1200, NULL,'10-20 min',5,
 22,
 'চেয়ারে বসে যোগা — বয়স্ক ও জয়েন্ট-ব্যথা।',
 'সিটিং ফরোয়ার্ড বেন্ড, টুইস্ট, ক্যাট-কাও, ব্রিদিং।',
 '{"chair"}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('yoga_cat_cow',       'ক্যাট-কাও',           'Cat-cow',
 'yoga','spine','low','beginner',
 5,300, NULL,'5-10 reps',3,
 8,
 'পিঠের মেরুদণ্ড নমনীয় করা।',
 'হাঁটু-হাত ভর, পিঠ ওপরে (ক্যাট) ও নিচে (কাও) আনুন।',
 '{"mat"}'::text[],
 true,true,false,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('yoga_child',         'চাইল্ডস পোজ',        'Child''s pose',
 'yoga','rest','low','beginner',
 5,300, NULL,'20-30 sec',3,
 5,
 'বিশ্রামের পোজ — পিঠ ও কাঁধ শিথিল।',
 'হাঁটু ভাঁজ, পিছনে বসুন, হাত সামনে প্রসারিত।',
 '{"mat"}'::text[],
 true,true,false,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('yoga_seated_twist',  'বসে টুইস্ট',          'Gentle seated twist',
 'yoga','spine','low','beginner',
 5,300, NULL,'10-30 sec/side',3,
 8,
 'পিঠের ঘূর্ণন — ডাইজেশন ও নমনীয়তা।',
 'চেয়ারে বসে এক দিকে ঘুরুন, ১৫-৩০ সেকেন্ড, বিপরীত দিকে।',
 '{"chair"}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('yoga_mountain',      'মাউন্টেন পোজ',       'Mountain pose',
 'yoga','standing','low','beginner',
 3,180, NULL,'30-60 sec',3,
 5,
 'ভঙ্গি সচেতনতা — ভারসাম্য ও শ্বাস।',
 'পা একসাথে, পিঠ সোজা, হাত পাশে, ৩০-৬০ সেকেন্ড দাঁড়ান।',
 '{}'::text[],
 true,true,true,true,
 true,true,
 true,true,true,true,
 NULL, NULL, NULL),

('yoga_side_bend',     'হালকা সাইড বেন্ড',   'Gentle side bend',
 'yoga','spine','low','beginner',
 5,300, NULL,'10-30 sec/side',3,
 8,
 'পাশের পেশি টানা — শ্বাসের সাথে।',
 'এক হাত মাথার ওপর, অন্য দিকে ধীরে ঝুঁকুন।',
 '{}'::text[],
 true,true,true,true,
 true,true,
 true,true,true,true,
 NULL, NULL, NULL),

('yoga_supported',     'সাপোর্টেড স্ট্যান্ডিং যোগা','Supported standing yoga',
 'yoga','standing','low','beginner',
 15,900, NULL,'10-15 min',3,
 18,
 'দেয়াল/চেয়ার সাপোর্টে স্ট্যান্ডিং যোগা পোজ।',
 'ওয়ার, ট্রি, ফরোয়ার্ড ফোল্ড — সাপোর্টসহ।',
 '{"chair"}'::text[],
 true,true,true,true,
 true,true,
 true,true,true,true,
 NULL, NULL, NULL),

('yoga_taichi',        'তাই চি',              'Tai chi',
 'yoga','mind_body','low','beginner',
 30,1800, NULL,'15-30 min',5,
 30,
 'ধীরে ধীরে সুন্দর নড়াচড়া — ব্যালেন্স ও শান্তি।',
 'সহজ ফর্ম সিকোয়েন্স অনুশীলন করুন, শ্বাসের সাথে সমন্বয়।',
 '{}'::text[],
 true,true,true,true,
 true,true,
 true,true,true,true,
 NULL, NULL, NULL),

-- ============================================================
-- 6. BREATHING / RELAXATION
-- ============================================================
('breath_deep',        'গভীর শ্বাস',           'Deep breathing',
 'breathing','relaxation','low','beginner',
 5,300, NULL,'5 min',7,
 4,
 'নাক দিয়ে শ্বাস নিয়ে মুখ দিয়ে ছাড়া — স্ট্রেস কমায়।',
 'চোখ বন্ধ, ৪ সেকেন্ড শ্বাস নিন, ৪ সেকেন্ড ছাড়ুন। ৫ মিনিট।',
 '{}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('breath_diaphragm',   'ডায়াফ্রামিক শ্বাস',   'Diaphragmatic breathing',
 'breathing','relaxation','low','beginner',
 10,600, NULL,'5-10 min',7,
 6,
 'পেট দিয়ে শ্বাস — রক্তচাপ কমায়।',
 'এক হাত বুকে, এক হাত পেটে; শ্বাসে পেট ফুলবে, বুক নয়।',
 '{}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('breath_slow',        'ধীর শ্বাস',           'Slow breathing',
 'breathing','relaxation','low','beginner',
 10,600, NULL,'5-10 min',7,
 6,
 'মিনিটে ৬-১০ বার শ্বাস — প্যারাসিমপ্যাথেটিক অ্যাক্টিভেশন।',
 '৪-৬ সেকেন্ড শ্বাস নিন, ৪-৬ সেকেন্ড ছাড়ুন।',
 '{}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('breath_box',         'বক্স ব্রিদিং',        'Box breathing',
 'breathing','relaxation','low','beginner',
 5,300, NULL,'3-5 min',7,
 5,
 '৪-৪-৪-৪ পদ্ধতি — স্ট্রেস ও রক্তচাপ কমায়।',
 '৪ সেকেন্ড শ্বাস নিন → ৪ সেকেন্ড ধরুন → ৪ সেকেন্ড ছাড়ুন → ৪ সেকেন্ড অপেক্ষা।',
 '{}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('breath_guided',      'গাইডেড রিল্যাক্সেশন', 'Guided relaxation',
 'breathing','relaxation','low','beginner',
 10,600, NULL,'5-10 min',7,
 5,
 'অডিও গাইডেন্সে শরীর শিথিল করা।',
 'চোখ বন্ধ, ধীরে শ্বাস, গাইডেড স্ক্রিপ্ট অনুসরণ করুন।',
 '{}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

('breath_mindful',     'মাইন্ডফুল ব্রিদিং',   'Mindful breathing',
 'breathing','mindfulness','low','beginner',
 10,600, NULL,'5-10 min',7,
 5,
 'শ্বাসের প্রতি মনোযোগ — অ্যানজাইটি কমায়।',
 'বসে বা শুয়ে শ্বাসের ওঠানামা পর্যবেক্ষণ করুন।',
 '{}'::text[],
 true,true,true,true,
 true,false,
 true,true,true,true,
 NULL, NULL, NULL),

-- ============================================================
-- 7. BANGLADESH-FRIENDLY PHYSICAL ACTIVITIES
-- ============================================================
('loc_walking_bazar',  'বাজারে হাঁটা',         'Walking to market',
 'walking','lifestyle','low','beginner',
 30,1800, NULL,'15-30 min',7,
 28,
 'বাজারে হেঁটে কেনাকাটা — কায়িক পরিশ্রম ও এরোবিক।',
 'মোটরবাইকের বদলে পায়ে হেঁটে বাজারে যান।',
 '{}'::text[],
 true,true,false,true,
 true,true,
 true,true,true,false,
 NULL,
 'ভারী ব্যাগ সমান দুই হাতে ভাগ করুন।',
 'অতিরিক্ত ওজন বহন করবেন না।'),

('loc_gardening',      'বাগান করা',           'Gardening',
 'household','lifestyle','low','beginner',
 30,1800, NULL,'15-30 min',5,
 35,
 'ছাদে বা বাড়ির আঙিনায় বাগান করা — হালকা-মাঝারি কাজ।',
 'গাছ লাগানো, পানি দেওয়া, আগাছা পরিষ্কার।',
 '{}'::text[],
 true,true,false,true,
 true,true,
 true,true,true,true,
 NULL,
 'হাঁটু ব্যথা হলে বসে কাজ করুন।',
 'কীটনাশক ব্যবহারে গ্লাভস পরুন।'),

('loc_yard_clean',     'উঠান পরিষ্কার',      'Yard cleaning',
 'household','lifestyle','low','beginner',
 20,1200, NULL,'15-30 min',5,
 28,
 'উঠান ঝাড়ু দেওয়া, পরিষ্কার করা।',
 'ঝাড়ু দিয়ে উঠান পরিষ্কার করুন, বসার ফাঁকে ফাঁকে বিশ্রাম।',
 '{"broom"}'::text[],
 true,true,false,true,
 true,true,
 true,true,true,true,
 NULL,
 'পিঠে ব্যথা হলে হ্যান্ডেল লম্বা ঝাড়ু ব্যবহার করুন।',
 NULL),

('loc_sweeping',       'ঘর ঝাড়ু দেওয়া',      'Sweeping the floor',
 'household','lifestyle','low','beginner',
 15,900, NULL,'10-20 min',5,
 20,
 'ঘর ঝাড়ু দেওয়া — হালকা কায়িক পরিশ্রম।',
 'প্রতি ঘর ২-৩ মিনিট, বসার ফাঁকে ফাঁকে বিশ্রাম।',
 '{"broom"}'::text[],
 true,true,true,true,
 true,true,
 true,true,true,true,
 NULL, NULL, NULL),

('loc_mopping',        'ঘর মোছা',             'Mopping',
 'household','lifestyle','medium','intermediate',
 20,1200, NULL,'15-20 min',5,
 30,
 'ঘর মুছা — মাঝারি তীব্রতার কাজ।',
 'লম্বা হ্যান্ডেলের মপ দিয়ে ঘর মুছুন, পিঠ সোজা রাখুন।',
 '{"mop"}'::text[],
 true,false,false,true,
 true,true,
 true,true,true,true,
 NULL,
 'ভেজা মেঝেতে পিছলে পড়ার ঝুঁকি — সতর্ক থাকুন।',
 'পিঠের তীব্র ব্যথা থাকলে এড়িয়ে চলুন।'),

('loc_cooking_stand',  'রান্নার সময় দাঁড়ানো','Standing while cooking',
 'household','lifestyle','low','beginner',
 30,1800, NULL,'15-30 min',7,
 18,
 'রান্নার সময় দাঁড়িয়ে থাকা — হালকা সক্রিয়তা।',
 'রান্নার ফাঁকে ফাঁকে ধীরে পায়চারি করুন।',
 '{}'::text[],
 true,true,true,true,
 true,true,
 true,true,true,true,
 NULL,
 'দীর্ঘ সময় দাঁড়িয়ে থাকলে পায়ে ব্যথা হতে পারে — মাঝে বসুন।',
 'ভারী পাত্র তোলার সময় হাঁটু ভাঁজ করুন।'),

('loc_washing_clothes','কাপড় ধোয়া',         'Washing clothes',
 'household','lifestyle','medium','intermediate',
 25,1500, NULL,'15-30 min',5,
 32,
 'হাতে কাপড় ধোয়া — মাঝারি কাজ।',
 'বসে বা দাঁড়িয়ে কাপড় ধুয়ে রিং করুন, পিঠ সোজা রাখুন।',
 '{}'::text[],
 true,true,false,true,
 true,true,
 true,true,true,true,
 NULL,
 'ঠান্ডা পানিতে দীর্ঘ সময় ধরলে জয়েন্টে ব্যথা হতে পারে।',
 'হার্নিয়া বা পিঠের তীব্র ব্যথা থাকলে এড়িয়ে চলুন।'),

('loc_farm_light',     'হালকা কৃষিকাজ',      'Light farming',
 'household','lifestyle','medium','intermediate',
 30,1800, NULL,'20-30 min',5,
 40,
 'হালকা কৃষি কাজ — মাঝারি তীব্রতা।',
 'আগাছা পরিষ্কার, চারা রোপণ, হালকা মাটি খন্ডা।',
 '{}'::text[],
 false,false,false,true,
 true,true,
 true,true,true,false,
 NULL,
 'রোদে দীর্ঘ সময় কাজ এড়িয়ে চলুন, পানি রাখুন।',
 NULL),

('loc_cycle_commute',  'সাইকেলে যাতায়াত',     'Cycling for commute',
 'cardio','lifestyle','medium','intermediate',
 25,1500, NULL,'15-30 min',5,
 35,
 'কাজে/বাজারে সাইকেলে যাওয়া — এরোবিক ও পরিবেশবান্ধব।',
 'নিরাপদ রাস্তায়, হেলমেট পরে সাইকেল চালান।',
 '{"bicycle"}'::text[],
 false,false,false,true,
 true,true,
 true,true,true,false,
 NULL,
 'ট্রাফিক-সচেতন থাকুন। সন্ধ্যায় রিফ্লেক্টর ব্যবহার করুন।',
 NULL)

on conflict (id) do update set
  name_bn = excluded.name_bn,
  name_en = excluded.name_en,
  category = excluded.category,
  sub_category = excluded.sub_category,
  intensity = excluded.intensity,
  difficulty = excluded.difficulty,
  duration_min = excluded.duration_min,
  target_duration_seconds = excluded.target_duration_seconds,
  sets = excluded.sets,
  repetitions = excluded.repetitions,
  frequency_per_week = excluded.frequency_per_week,
  target_calories_kcal = excluded.target_calories_kcal,
  description_bn = excluded.description_bn,
  instructions_bn = excluded.instructions_bn,
  equipment = excluded.equipment,
  beginner = excluded.beginner,
  elderly_friendly = excluded.elderly_friendly,
  chair_supported = excluded.chair_supported,
  low_impact = excluded.low_impact,
  joint_friendly = excluded.joint_friendly,
  balance_required = excluded.balance_required,
  diabetes_suitable = excluded.diabetes_suitable,
  hypertension_suitable = excluded.hypertension_suitable,
  obesity_suitable = excluded.obesity_suitable,
  anemia_suitable = excluded.anemia_suitable,
  video_url = excluded.video_url,
  safety_notes_bn = excluded.safety_notes_bn,
  contraindications = excluded.contraindications,
  is_active = true;